{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-android",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4irbk5x6kragle63hngfxoqfii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-android-1.6.1.jar",
          "url": "kotlinx-coroutines-android-1.6.1.jar",
          "size": 19515,
          "sha512": "14b99c72268256b36b9ec71147edf63832857b4f79627256572f9ab699fd147dda8989487d33104e6e17d2bac488e5b441298d086b5e8fd944e0fa69b9b7ed4c",
          "sha256": "961ebde8138779a299430ca325a86e28c490527a87ba518362fa45c44c7e7e95",
          "sha1": "4e61fcdcc508cbaa37c4a284a50205d7c7767e37",
          "md5": "e427aac656a3159609ea059d38feaf7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-android-1.6.1.jar",
          "url": "kotlinx-coroutines-android-1.6.1.jar",
          "size": 19515,
          "sha512": "14b99c72268256b36b9ec71147edf63832857b4f79627256572f9ab699fd147dda8989487d33104e6e17d2bac488e5b441298d086b5e8fd944e0fa69b9b7ed4c",
          "sha256": "961ebde8138779a299430ca325a86e28c490527a87ba518362fa45c44c7e7e95",
          "sha1": "4e61fcdcc508cbaa37c4a284a50205d7c7767e37",
          "md5": "e427aac656a3159609ea059d38feaf7f"
        }
      ]
    }
  ]
}
